//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teller.IntegradorReal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdclienteField;
        
        private int IdcuentasField;
        
        private int BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Idcliente {
            get {
                return this.IdclienteField;
            }
            set {
                if ((this.IdclienteField.Equals(value) != true)) {
                    this.IdclienteField = value;
                    this.RaisePropertyChanged("Idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Idcuentas {
            get {
                return this.IdcuentasField;
            }
            set {
                if ((this.IdcuentasField.Equals(value) != true)) {
                    this.IdcuentasField = value;
                    this.RaisePropertyChanged("Idcuentas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegradorReal.IntegradorSoap")]
    public interface IntegradorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Teller.IntegradorReal.HelloWorldResponse HelloWorld(Teller.IntegradorReal.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.IntegradorReal.HelloWorldResponse> HelloWorldAsync(Teller.IntegradorReal.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuenta", ReplyAction="*")]
        Teller.IntegradorReal.getCuentaResponse getCuenta(Teller.IntegradorReal.getCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.IntegradorReal.getCuentaResponse> getCuentaAsync(Teller.IntegradorReal.getCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Teller.IntegradorReal.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Teller.IntegradorReal.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.IntegradorReal.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Teller.IntegradorReal.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Teller.IntegradorReal.getCuentaRequestBody Body;
        
        public getCuentaRequest() {
        }
        
        public getCuentaRequest(Teller.IntegradorReal.getCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public getCuentaRequestBody() {
        }
        
        public getCuentaRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.IntegradorReal.getCuentaResponseBody Body;
        
        public getCuentaResponse() {
        }
        
        public getCuentaResponse(Teller.IntegradorReal.getCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Teller.IntegradorReal.Cuenta getCuentaResult;
        
        public getCuentaResponseBody() {
        }
        
        public getCuentaResponseBody(Teller.IntegradorReal.Cuenta getCuentaResult) {
            this.getCuentaResult = getCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegradorSoapChannel : Teller.IntegradorReal.IntegradorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegradorSoapClient : System.ServiceModel.ClientBase<Teller.IntegradorReal.IntegradorSoap>, Teller.IntegradorReal.IntegradorSoap {
        
        public IntegradorSoapClient() {
        }
        
        public IntegradorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegradorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.IntegradorReal.HelloWorldResponse Teller.IntegradorReal.IntegradorSoap.HelloWorld(Teller.IntegradorReal.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Teller.IntegradorReal.HelloWorldRequest inValue = new Teller.IntegradorReal.HelloWorldRequest();
            inValue.Body = new Teller.IntegradorReal.HelloWorldRequestBody();
            Teller.IntegradorReal.HelloWorldResponse retVal = ((Teller.IntegradorReal.IntegradorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.IntegradorReal.HelloWorldResponse> Teller.IntegradorReal.IntegradorSoap.HelloWorldAsync(Teller.IntegradorReal.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.IntegradorReal.HelloWorldResponse> HelloWorldAsync() {
            Teller.IntegradorReal.HelloWorldRequest inValue = new Teller.IntegradorReal.HelloWorldRequest();
            inValue.Body = new Teller.IntegradorReal.HelloWorldRequestBody();
            return ((Teller.IntegradorReal.IntegradorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.IntegradorReal.getCuentaResponse Teller.IntegradorReal.IntegradorSoap.getCuenta(Teller.IntegradorReal.getCuentaRequest request) {
            return base.Channel.getCuenta(request);
        }
        
        public Teller.IntegradorReal.Cuenta getCuenta(string cedula) {
            Teller.IntegradorReal.getCuentaRequest inValue = new Teller.IntegradorReal.getCuentaRequest();
            inValue.Body = new Teller.IntegradorReal.getCuentaRequestBody();
            inValue.Body.cedula = cedula;
            Teller.IntegradorReal.getCuentaResponse retVal = ((Teller.IntegradorReal.IntegradorSoap)(this)).getCuenta(inValue);
            return retVal.Body.getCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.IntegradorReal.getCuentaResponse> Teller.IntegradorReal.IntegradorSoap.getCuentaAsync(Teller.IntegradorReal.getCuentaRequest request) {
            return base.Channel.getCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.IntegradorReal.getCuentaResponse> getCuentaAsync(string cedula) {
            Teller.IntegradorReal.getCuentaRequest inValue = new Teller.IntegradorReal.getCuentaRequest();
            inValue.Body = new Teller.IntegradorReal.getCuentaRequestBody();
            inValue.Body.cedula = cedula;
            return ((Teller.IntegradorReal.IntegradorSoap)(this)).getCuentaAsync(inValue);
        }
    }
}
