//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teller.Integrador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nacionalidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.cedulaField, value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nacionalidadField, value) != true)) {
                    this.nacionalidadField = value;
                    this.RaisePropertyChanged("nacionalidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int tipoField;
        
        private int idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedulaClienteField;
        
        private long balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cedulaCliente {
            get {
                return this.cedulaClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cedulaClienteField, value) != true)) {
                    this.cedulaClienteField = value;
                    this.RaisePropertyChanged("cedulaCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TipoMoneda {
            get {
                return this.TipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMonedaField, value) != true)) {
                    this.TipoMonedaField = value;
                    this.RaisePropertyChanged("TipoMoneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Integrador.TellerServicesSoap")]
    public interface TellerServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Teller.Integrador.HelloWorldResponse HelloWorld(Teller.Integrador.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.Integrador.HelloWorldResponse> HelloWorldAsync(Teller.Integrador.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCliente", ReplyAction="*")]
        Teller.Integrador.getClienteResponse getCliente(Teller.Integrador.getClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.Integrador.getClienteResponse> getClienteAsync(Teller.Integrador.getClienteRequest request);
        
        // CODEGEN: Generating message contract since element name getCuentaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuenta", ReplyAction="*")]
        Teller.Integrador.getCuentaResponse getCuenta(Teller.Integrador.getCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.Integrador.getCuentaResponse> getCuentaAsync(Teller.Integrador.getCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hacerRetiro", ReplyAction="*")]
        bool hacerRetiro(int idCuenta, long monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hacerRetiro", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> hacerRetiroAsync(int idCuenta, long monto);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hacerDeposito", ReplyAction="*")]
        Teller.Integrador.hacerDepositoResponse hacerDeposito(Teller.Integrador.hacerDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hacerDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<Teller.Integrador.hacerDepositoResponse> hacerDepositoAsync(Teller.Integrador.hacerDepositoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Teller.Integrador.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Teller.Integrador.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCliente", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.getClienteRequestBody Body;
        
        public getClienteRequest() {
        }
        
        public getClienteRequest(Teller.Integrador.getClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public getClienteRequestBody() {
        }
        
        public getClienteRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.getClienteResponseBody Body;
        
        public getClienteResponse() {
        }
        
        public getClienteResponse(Teller.Integrador.getClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Teller.Integrador.Cliente getClienteResult;
        
        public getClienteResponseBody() {
        }
        
        public getClienteResponseBody(Teller.Integrador.Cliente getClienteResult) {
            this.getClienteResult = getClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.getCuentaRequestBody Body;
        
        public getCuentaRequest() {
        }
        
        public getCuentaRequest(Teller.Integrador.getCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getCuentaRequestBody() {
        }
        
        public getCuentaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.getCuentaResponseBody Body;
        
        public getCuentaResponse() {
        }
        
        public getCuentaResponse(Teller.Integrador.getCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Teller.Integrador.Cuenta getCuentaResult;
        
        public getCuentaResponseBody() {
        }
        
        public getCuentaResponseBody(Teller.Integrador.Cuenta getCuentaResult) {
            this.getCuentaResult = getCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hacerDepositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hacerDeposito", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.hacerDepositoRequestBody Body;
        
        public hacerDepositoRequest() {
        }
        
        public hacerDepositoRequest(Teller.Integrador.hacerDepositoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hacerDepositoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string concepto;
        
        public hacerDepositoRequestBody() {
        }
        
        public hacerDepositoRequestBody(long monto, int cuenta, string cedula, string concepto) {
            this.monto = monto;
            this.cuenta = cuenta;
            this.cedula = cedula;
            this.concepto = concepto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hacerDepositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hacerDepositoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Teller.Integrador.hacerDepositoResponseBody Body;
        
        public hacerDepositoResponse() {
        }
        
        public hacerDepositoResponse(Teller.Integrador.hacerDepositoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hacerDepositoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool hacerDepositoResult;
        
        public hacerDepositoResponseBody() {
        }
        
        public hacerDepositoResponseBody(bool hacerDepositoResult) {
            this.hacerDepositoResult = hacerDepositoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TellerServicesSoapChannel : Teller.Integrador.TellerServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TellerServicesSoapClient : System.ServiceModel.ClientBase<Teller.Integrador.TellerServicesSoap>, Teller.Integrador.TellerServicesSoap {
        
        public TellerServicesSoapClient() {
        }
        
        public TellerServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TellerServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TellerServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TellerServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.Integrador.HelloWorldResponse Teller.Integrador.TellerServicesSoap.HelloWorld(Teller.Integrador.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Teller.Integrador.HelloWorldRequest inValue = new Teller.Integrador.HelloWorldRequest();
            inValue.Body = new Teller.Integrador.HelloWorldRequestBody();
            Teller.Integrador.HelloWorldResponse retVal = ((Teller.Integrador.TellerServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.Integrador.HelloWorldResponse> Teller.Integrador.TellerServicesSoap.HelloWorldAsync(Teller.Integrador.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.Integrador.HelloWorldResponse> HelloWorldAsync() {
            Teller.Integrador.HelloWorldRequest inValue = new Teller.Integrador.HelloWorldRequest();
            inValue.Body = new Teller.Integrador.HelloWorldRequestBody();
            return ((Teller.Integrador.TellerServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.Integrador.getClienteResponse Teller.Integrador.TellerServicesSoap.getCliente(Teller.Integrador.getClienteRequest request) {
            return base.Channel.getCliente(request);
        }
        
        public Teller.Integrador.Cliente getCliente(string cedula) {
            Teller.Integrador.getClienteRequest inValue = new Teller.Integrador.getClienteRequest();
            inValue.Body = new Teller.Integrador.getClienteRequestBody();
            inValue.Body.cedula = cedula;
            Teller.Integrador.getClienteResponse retVal = ((Teller.Integrador.TellerServicesSoap)(this)).getCliente(inValue);
            return retVal.Body.getClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.Integrador.getClienteResponse> Teller.Integrador.TellerServicesSoap.getClienteAsync(Teller.Integrador.getClienteRequest request) {
            return base.Channel.getClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.Integrador.getClienteResponse> getClienteAsync(string cedula) {
            Teller.Integrador.getClienteRequest inValue = new Teller.Integrador.getClienteRequest();
            inValue.Body = new Teller.Integrador.getClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((Teller.Integrador.TellerServicesSoap)(this)).getClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.Integrador.getCuentaResponse Teller.Integrador.TellerServicesSoap.getCuenta(Teller.Integrador.getCuentaRequest request) {
            return base.Channel.getCuenta(request);
        }
        
        public Teller.Integrador.Cuenta getCuenta(int id) {
            Teller.Integrador.getCuentaRequest inValue = new Teller.Integrador.getCuentaRequest();
            inValue.Body = new Teller.Integrador.getCuentaRequestBody();
            inValue.Body.id = id;
            Teller.Integrador.getCuentaResponse retVal = ((Teller.Integrador.TellerServicesSoap)(this)).getCuenta(inValue);
            return retVal.Body.getCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.Integrador.getCuentaResponse> Teller.Integrador.TellerServicesSoap.getCuentaAsync(Teller.Integrador.getCuentaRequest request) {
            return base.Channel.getCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.Integrador.getCuentaResponse> getCuentaAsync(int id) {
            Teller.Integrador.getCuentaRequest inValue = new Teller.Integrador.getCuentaRequest();
            inValue.Body = new Teller.Integrador.getCuentaRequestBody();
            inValue.Body.id = id;
            return ((Teller.Integrador.TellerServicesSoap)(this)).getCuentaAsync(inValue);
        }
        
        public bool hacerRetiro(int idCuenta, long monto) {
            return base.Channel.hacerRetiro(idCuenta, monto);
        }
        
        public System.Threading.Tasks.Task<bool> hacerRetiroAsync(int idCuenta, long monto) {
            return base.Channel.hacerRetiroAsync(idCuenta, monto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teller.Integrador.hacerDepositoResponse Teller.Integrador.TellerServicesSoap.hacerDeposito(Teller.Integrador.hacerDepositoRequest request) {
            return base.Channel.hacerDeposito(request);
        }
        
        public bool hacerDeposito(long monto, int cuenta, string cedula, string concepto) {
            Teller.Integrador.hacerDepositoRequest inValue = new Teller.Integrador.hacerDepositoRequest();
            inValue.Body = new Teller.Integrador.hacerDepositoRequestBody();
            inValue.Body.monto = monto;
            inValue.Body.cuenta = cuenta;
            inValue.Body.cedula = cedula;
            inValue.Body.concepto = concepto;
            Teller.Integrador.hacerDepositoResponse retVal = ((Teller.Integrador.TellerServicesSoap)(this)).hacerDeposito(inValue);
            return retVal.Body.hacerDepositoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teller.Integrador.hacerDepositoResponse> Teller.Integrador.TellerServicesSoap.hacerDepositoAsync(Teller.Integrador.hacerDepositoRequest request) {
            return base.Channel.hacerDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teller.Integrador.hacerDepositoResponse> hacerDepositoAsync(long monto, int cuenta, string cedula, string concepto) {
            Teller.Integrador.hacerDepositoRequest inValue = new Teller.Integrador.hacerDepositoRequest();
            inValue.Body = new Teller.Integrador.hacerDepositoRequestBody();
            inValue.Body.monto = monto;
            inValue.Body.cuenta = cuenta;
            inValue.Body.cedula = cedula;
            inValue.Body.concepto = concepto;
            return ((Teller.Integrador.TellerServicesSoap)(this)).hacerDepositoAsync(inValue);
        }
    }
}
